### ISSUE TITLE
i cant run jesse

### ISSUE THREAD

**Issue by anakein** [jesse-ai/project-template#2]
I have jesse installed in raspberry 4 ( follow instruction inside here)

postgree is working 

postgres=# \du
 jesse_2       |                                                            | {}
 jesse_user    |                                                            | {}

postgres=# \l
 jesse_db  | postgres | UTF8         | es_ES.UTF-8 | es_ES.UTF-8 | =Tc/postgres           +
           |          |              |             |             | postgres=CTc/postgres  +
           |          |              |             |             | jesse_user=CTc/postgres+
           |          |              |             |             | jesse_2=CTc/postgres

and my .env 

# If not using docker, you probably want to set this to "localhost"
#POSTGRES_HOST=postgres
POSTGRES_HOST=localhost
POSTGRES_NAME=jesse_db
POSTGRES_PORT=5432
POSTGRES_USERNAME=jesse_user
POSTGRES_PASSWORD=password

# If not using docker, you probably want to set this to "localhost"
REDIS_HOST=localhost
#REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=

BUT.........

Tbot@TradingBot:~/Tbot $ jesse run
Running database migrations...
Database wasn't ready. Sleep for 10 seconds and try again.
Running database migrations...
Traceback (most recent call last):
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
  File "/home/Tbot/.local/lib/python3.9/site-packages/playhouse/postgres_ext.py", line 467, in _connect
    conn = super(PostgresqlExtDatabase, self)._connect()
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3801, in _connect
    conn = psycopg2.connect(**params)
  File "/home/Tbot/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Tbot/jesse/jesse/__init__.py", line 206, in run
    run_migrations()
  File "/home/Tbot/jesse/jesse/services/migrator.py", line 16, in run
    database.open_connection()
  File "/home/Tbot/jesse/jesse/services/db.py", line 58, in open_connection
    self.db.connect()
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3099, in connect
    self._initialize_connection(self._state.conn)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
  File "/home/Tbot/.local/lib/python3.9/site-packages/playhouse/postgres_ext.py", line 467, in _connect
    conn = super(PostgresqlExtDatabase, self)._connect()
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3801, in _connect
    conn = psycopg2.connect(**params)
  File "/home/Tbot/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: SCRAM authentication requires libpq version 10 or above

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
  File "/home/Tbot/.local/lib/python3.9/site-packages/playhouse/postgres_ext.py", line 467, in _connect
    conn = super(PostgresqlExtDatabase, self)._connect()
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3801, in _connect
    conn = psycopg2.connect(**params)
  File "/home/Tbot/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3158, in execute_sql
    cursor = self.cursor(commit)
  File "/home/Tbot/.local/lib/python3.9/site-packages/playhouse/postgres_ext.py", line 475, in cursor
    self.connect()
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3099, in connect
    self._initialize_connection(self._state.conn)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
  File "/home/Tbot/.local/lib/python3.9/site-packages/playhouse/postgres_ext.py", line 467, in _connect
    conn = super(PostgresqlExtDatabase, self)._connect()
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3801, in _connect
    conn = psycopg2.connect(**params)
  File "/home/Tbot/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: SCRAM authentication requires libpq version 10 or above

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Tbot/.local/bin/jesse", line 33, in <module>
    sys.exit(load_entry_point('jesse', 'console_scripts', 'jesse')())
  File "/home/Tbot/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/Tbot/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/Tbot/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/Tbot/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/Tbot/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/Tbot/jesse/jesse/__init__.py", line 211, in run
    run_migrations()
  File "/home/Tbot/jesse/jesse/services/migrator.py", line 21, in run
    _candle(migrator)
  File "/home/Tbot/jesse/jesse/services/migrator.py", line 40, in _candle
    if 'candle' in database.db.get_tables():
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3835, in get_tables
    cursor = self.execute_sql(query, (schema or 'public',))
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3167, in execute_sql
    self.commit()
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3158, in execute_sql
    cursor = self.cursor(commit)
  File "/home/Tbot/.local/lib/python3.9/site-packages/playhouse/postgres_ext.py", line 475, in cursor
    self.connect()
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3099, in connect
    self._initialize_connection(self._state.conn)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
  File "/home/Tbot/.local/lib/python3.9/site-packages/playhouse/postgres_ext.py", line 467, in _connect
    conn = super(PostgresqlExtDatabase, self)._connect()
  File "/home/Tbot/.local/lib/python3.9/site-packages/peewee.py", line 3801, in _connect
    conn = psycopg2.connect(**params)
  File "/home/Tbot/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: SCRAM authentication requires libpq version 10 or above

**Comment by saleh-mir** [comment]
I have not installed Jesse on an ARM Linux machine so far. Based on your errors looks like the postgres package for Python is not installed:
```
peewee.OperationalError: SCRAM authentication requires libpq version 10 or above
```

I suggest asking on the discord group as I know there are others who have tried installing Jesse on RP:
https://jesse.trade/discord
